# network Config
networks:
  sbnuxt_network:
    name: sbnuxt_network
    driver: bridge

# Service config
services:
  # Postgres
  postgresdb: #service name
    image: postgres:15.8
    container_name: postgresdb
    volumes:
      - ./postgresdb:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 257890
      POSTGRES_DB: springstoreapi
    ports:
      - "6432:5432"
    restart: always
    networks:
      - sbnuxt_network

  # Spring Boot
  # springapi:
  #   container_name: springapi
  #   build:
  #     context: ./SpringAPI
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./SpringAPI:/.SpringAPI/app
  #   environment:
  #     - SPRING_PROFILES_ACTIVE=prod
  #   ports:
  #     - "9090:8080"
  #   restart: always
  #   depends_on:
  #     - postgresdb
  #   networks:
  #     - sbnuxt_network

    # Spring Boot
  springapi:
    container_name: springapi
    build:
      context: ./SpringAPI
      dockerfile: Dockerfile
    volumes:
      - ./SpringAPI:/.SpringAPI/app
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "9090:8080"
    restart: always
    depends_on:
      - postgresdb
    networks:
      - sbnuxt_network

  # Nuxt.js
  nuxtapp:
    container_name: nuxtapp
    build:
      context: ./NuxtApp
      dockerfile: Dockerfile
    volumes:
      - ./NuxtApp:/.NuxtApp/app #ดึงมา
      - /app/node_modules # bookmarks valume ่ไม่ตึงมา
    environment:
      NODE_ENV: production
    ports:
      - "3300:3000"
    restart: always
    depends_on:
      - springapi
    networks:
      - sbnuxt_network